module BasicTypeAndValues {
    const integer   c_uInt1Max := 1;
    const integer   c_uInt2Max := 3;
    const integer   c_uInt3Max := 7;
    const integer   c_uInt4Max := 15;
    const integer   c_uInt5Max := 31;
    const integer   c_uInt6Max := 63;
    const integer   c_uInt7Max := 127;
    const integer   c_uInt8Max := 255;
    const integer   c_uInt9Max := 511;
    const integer   c_uInt10Max := 1023;
    const integer   c_uInt11Max := 2047;
    const integer   c_uInt12Max := 4095;
    const integer   c_uInt13Max := 8191;
    const integer   c_uInt14Max := 16383;
    const integer   c_uInt15Max := 32767;
    const integer   c_uInt16Max := 65535;
    const integer   c_uInt17Max := 131071;
    const integer   c_uInt18Max := 262143;
    const integer   c_uInt19Max := 524287;
    const integer   c_uInt20Max := 1048575;
    const integer   c_uInt21Max := 2097151;
    const integer   c_uInt22Max := 4194303;
    const integer   c_uInt23Max := 8388607;
    const integer   c_uInt24Max := 16777215;
    const integer   c_uInt25Max := 33554431;
    const integer   c_uInt26Max := 67108863;
    const integer   c_uInt27Max := 134217727;
    const integer   c_uInt28Max := 268435456;
    const integer   c_uInt29Max := 536870911;
    const integer   c_uInt30Max := 1073741823;
    const integer   c_uInt31Max := 2147483647;
    const integer   c_uInt32Max := 4294967295;
    const integer   c_uInt48Max := 281474976710655;
    const integer   c_uInt64Max := 18446744073709551615;

    type integer    UInt  (0 .. infinity);
    type integer    UInt1 (0 .. c_uInt1Max) with {variant Length(1); Signed(false);};
    type integer    UInt2 (0 .. c_uInt2Max) with {variant Length(2); Signed(false);};
    type integer    UInt3 (0 .. c_uInt3Max) with {variant Length(3); Signed(false);};
    type integer    UInt4 (0 .. c_uInt4Max) with {variant Length(4); Signed(false);};
    type integer    UInt5 (0 .. c_uInt5Max) with {variant Length(5); Signed(false);};
    type integer    UInt6 (0 .. c_uInt6Max) with {variant Length(6); Signed(false);};
    type integer    UInt7 (0 .. c_uInt7Max) with {variant Length(7); Signed(false);};
    type integer    UInt8 (0 .. c_uInt8Max) with {variant Length(8); Signed(false);};
    type integer    UInt9 (0 .. c_uInt9Max) with {variant Length(9); Signed(false);};
    type integer    UInt10 (0 .. c_uInt10Max) with {variant Length(10); Signed(false);};
    type integer    UInt11 (0 .. c_uInt11Max) with {variant Length(11); Signed(false);};
    type integer    UInt12 (0 .. c_uInt12Max) with {variant Length(12); Signed(false);};
    type integer    UInt13 (0 .. c_uInt13Max) with {variant Length(13); Signed(false);};
    type integer    UInt14 (0 .. c_uInt14Max) with {variant Length(14); Signed(false);};
    type integer    UInt15 (0 .. c_uInt15Max) with {variant Length(15); Signed(false);};
    type integer    UInt16 (0 .. c_uInt16Max) with {variant Length(16); Signed(false);};
    type integer    UInt17 (0 .. c_uInt17Max) with {variant Length(17); Signed(false);};
    type integer    UInt18 (0 .. c_uInt18Max) with {variant Length(18); Signed(false);};
    type integer    UInt19 (0 .. c_uInt19Max) with {variant Length(19); Signed(false);};
    type integer    UInt20 (0 .. c_uInt20Max) with {variant Length(20); Signed(false);};
    type integer    UInt21 (0 .. c_uInt21Max) with {variant Length(21); Signed(false);};
    type integer    UInt22 (0 .. c_uInt22Max) with {variant Length(22); Signed(false);};
    type integer    UInt23 (0 .. c_uInt23Max) with {variant Length(23); Signed(false);};
    type integer    UInt24 (0 .. c_uInt24Max) with {variant Length(24); Signed(false);};
    type integer    UInt25 (0 .. c_uInt25Max) with {variant Length(25); Signed(false);};
    type integer    UInt26 (0 .. c_uInt26Max) with {variant Length(26); Signed(false);};
    type integer    UInt27 (0 .. c_uInt27Max) with {variant Length(27); Signed(false);};
    type integer    UInt28 (0 .. c_uInt28Max) with {variant Length(28); Signed(false);};
    type integer    UInt29 (0 .. c_uInt29Max) with {variant Length(29); Signed(false);};
    type integer    UInt30 (0 .. c_uInt30Max) with {variant Length(30); Signed(false);};
    type integer    UInt31 (0 .. c_uInt31Max) with {variant Length(31); Signed(false);};
    type integer    UInt32 (0 .. c_uInt32Max) with {variant Length(32); Signed(false);};
    type integer    UInt48 (0 .. c_uInt48Max) with {variant Length(48); Signed(false);};
    type integer    UInt64 (0 .. c_uInt64Max) with {variant Length(64); Signed(false);};

    const integer   c_int1Min := -1;
    const integer   c_int1Max := 0;
    const integer   c_int2Min := -2;
    const integer   c_int2Max := 1;
    const integer   c_int3Min := -4;
    const integer   c_int3Max := 3;
    const integer   c_int4Min := -8;
    const integer   c_int4Max := 7;
    const integer   c_int5Min := -16;
    const integer   c_int5Max := 15;
    const integer   c_int6Min := -32;
    const integer   c_int6Max := 31;
    const integer   c_int7Min := -64;
    const integer   c_int7Max := 63;
    const integer   c_int8Min := -128;
    const integer   c_int8Max := 127;
    const integer   c_int9Min := -256;
    const integer   c_int9Max := 255;
    const integer   c_int10Min := -512;
    const integer   c_int10Max := 511;
    const integer   c_int11Min := -1024;
    const integer   c_int11Max := 1023;
    const integer   c_int12Min := -2048;
    const integer   c_int12Max := 2047;
    const integer   c_int13Min := -4096;
    const integer   c_int13Max := 4095;
    const integer   c_int14Min := -8192;
    const integer   c_int14Max := 8191;
    const integer   c_int15Min := -16384;
    const integer   c_int15Max := 16383;
    const integer   c_int16Min := -32768;
    const integer   c_int16Max := 32767;
    const integer   c_int17Min := -65536;
    const integer   c_int17Max := 65535;
    const integer   c_int18Min := -131072;
    const integer   c_int18Max := 131071;
    const integer   c_int19Min := -262144;
    const integer   c_int19Max := 262143;
    const integer   c_int20Min := -524288;
    const integer   c_int20Max := 524287;
    const integer   c_int21Min := -1048576;
    const integer   c_int21Max := 1048575;
    const integer   c_int22Min := -2097152;
    const integer   c_int22Max := 2097151;
    const integer   c_int23Min := -4194304;
    const integer   c_int23Max := 4194303;
    const integer   c_int24Min := -8388608;
    const integer   c_int24Max := 8388607;
    const integer   c_int25Min := -16777216;
    const integer   c_int25Max := 16777215;
    const integer   c_int26Min := -33554432;
    const integer   c_int26Max := 33554431;
    const integer   c_int27Min := -67108864;
    const integer   c_int27Max := 67108863;
    const integer   c_int28Min := -134217728;
    const integer   c_int28Max := 134217727;
    const integer   c_int29Min := -268435456;
    const integer   c_int29Max := 268435456;
    const integer   c_int30Min := -536870912;
    const integer   c_int30Max := 536870911;
    const integer   c_int31Min := -1073741824;
    const integer   c_int31Max := 1073741823;
    const integer   c_int32Min := -2147483648;
    const integer   c_int32Max := 2147483647;

    type integer    Int;
    type integer    Int1  (c_int1Min .. c_int1Max) with { variant Length(1) };
    type integer    Int2  (c_int2Min .. c_int2Max) with { variant Length(2) };
    type integer    Int3  (c_int3Min .. c_int3Max) with { variant Length(3) };
    type integer    Int4  (c_int4Min .. c_int4Max) with { variant Length(4) };
    type integer    Int5  (c_int5Min .. c_int5Max) with { variant Length(5) };
    type integer    Int6  (c_int6Min .. c_int6Max) with { variant Length(6) };
    type integer    Int7  (c_int7Min .. c_int7Max) with { variant Length(7) };
    type integer    Int8  (c_int8Min .. c_int8Max) with { variant Length(8) };
    type integer    Int9  (c_int9Min .. c_int9Max) with { variant Length(9) };
    type integer    Int10  (c_int10Min .. c_int10Max) with { variant Length(10) };
    type integer    Int11  (c_int11Min .. c_int11Max) with { variant Length(11) };
    type integer    Int12  (c_int12Min .. c_int12Max) with { variant Length(12) };
    type integer    Int13  (c_int13Min .. c_int13Max) with { variant Length(13) };
    type integer    Int14  (c_int14Min .. c_int14Max) with { variant Length(14) };
    type integer    Int15  (c_int15Min .. c_int15Max) with { variant Length(15) };
    type integer    Int16  (c_int16Min .. c_int16Max) with { variant Length(16) };
    type integer    Int17  (c_int17Min .. c_int17Max) with { variant Length(17) };
    type integer    Int18  (c_int18Min .. c_int18Max) with { variant Length(18) };
    type integer    Int19  (c_int19Min .. c_int19Max) with { variant Length(19) };
    type integer    Int20  (c_int20Min .. c_int20Max) with { variant Length(20) };
    type integer    Int21  (c_int21Min .. c_int21Max) with { variant Length(21) };
    type integer    Int22  (c_int22Min .. c_int22Max) with { variant Length(22) };
    type integer    Int23  (c_int23Min .. c_int23Max) with { variant Length(23) };
    type integer    Int24  (c_int24Min .. c_int24Max) with { variant Length(24) };
    type integer    Int25  (c_int25Min .. c_int25Max) with { variant Length(25) };
    type integer    Int26  (c_int26Min .. c_int26Max) with { variant Length(26) };
    type integer    Int27  (c_int27Min .. c_int27Max) with { variant Length(27) };
    type integer    Int28  (c_int28Min .. c_int28Max) with { variant Length(28) };
    type integer    Int29  (c_int29Min .. c_int29Max) with { variant Length(29) };
    type integer    Int30  (c_int30Min .. c_int30Max) with { variant Length(30) };
    type integer    Int31  (c_int31Min .. c_int31Max) with { variant Length(31) };
    type integer    Int32  (c_int32Min .. c_int32Max) with { variant Length(32) };

    /* 
     * Number in name indicates string length in number of 
     *         _bits_
     */
    type bitstring  Bit1    length(1);
    type bitstring  Bit2    length(2);
    type bitstring  Bit3    length(3);
    type bitstring  Bit4    length(4);
    type bitstring  Bit5    length(5);
    type bitstring  Bit6    length(6);
    type bitstring  Bit7    length(7);
    type bitstring  Bit8    length(8);
    type bitstring  Bit9    length(9);
    type bitstring  Bit10   length(10);
    type bitstring  Bit11   length(11);
    type bitstring  Bit12   length(12);
    type bitstring  Bit13   length(13);
    type bitstring  Bit14   length(14);
    type bitstring  Bit15   length(15);
    type bitstring  Bit16   length(16);
    type bitstring  Bit17   length(17);
    type bitstring  Bit18   length(18);
    type bitstring  Bit19   length(19);
    type bitstring  Bit20   length(20);
    type bitstring  Bit21   length(21);
    type bitstring  Bit22   length(22);
    type bitstring  Bit23   length(23);
    type bitstring  Bit24   length(24);
    type bitstring  Bit25   length(25);
    type bitstring  Bit26   length(26);
    type bitstring  Bit27   length(27);
    type bitstring  Bit28   length(28);
    type bitstring  Bit29   length(29);
    type bitstring  Bit30   length(30);
    type bitstring  Bit31   length(31);
    type bitstring  Bit32   length(32);

    type bitstring  Bit48   length(48);
    type bitstring  Bit64   length(64); 
    type bitstring  Bit128  length(128);   
    
    /* 
     * Number in name indicates string length in number of 
     *         _octets_
     */
    type octetstring    Oct1    length(1);
    type octetstring    Oct2    length(2);
    type octetstring    Oct3    length(3);
    type octetstring    Oct4    length(4);
    type octetstring    Oct5    length(5);
    type octetstring    Oct6    length(6);
    type octetstring    Oct7    length(7);
    type octetstring    Oct8    length(8);
    type octetstring    Oct9    length(9);
    type octetstring    Oct10   length(10);
    type octetstring    Oct11   length(11);
    type octetstring    Oct12   length(12);
    type octetstring    Oct13   length(13);
    type octetstring    Oct14   length(14);
    type octetstring    Oct15   length(15);
    type octetstring    Oct16   length(16);
    type octetstring    Oct20   length(20);
    type octetstring    Oct24   length(24);

    type octetstring    Oct80   length(80);
    type octetstring    Oct128  length(128);
    type octetstring    Oct160  length(160);
    type octetstring    Oct320  length(320);
    type octetstring    Oct640  length(640);
    type octetstring    Oct1280 length(1280);
    type octetstring    Oct1380 length(1380);

    type octetstring    Oct0to255   length(0 .. 255);
    type octetstring    Oct1to15    length(1 .. 15);
    type octetstring    Oct6to15    length(6 .. 15);
    type octetstring    Oct1to128   length(1 .. 128);
    type octetstring    Oct1to254   length(1 .. 254);
    type octetstring    Oct1to255   length(1 .. 255);

    /*
     * @desc Mac Address
    */
    type Oct6 MacAddress with {
        variant Format(MAC_ADDRESS);
    }
    
    /*
     * @desc IPv4 Address
    */
    type Oct4 Ipv4Address with {
        variant Format(IPV4_ADDRESS)
    }
    
    /*
     * @desc IPv6 Address
    */
    type Oct16 Ipv6Address with {
        variant Format(IPV6_ADDRESS)
    }
    
} with {
    encode "FPB"
}
