OUTPUT_LIB_FOLD = ..

LIB=$(FPB_LIB)

#source path
FILE= AutotestUtil \
	TextBitset \
	Processing \
	J_TextBitset \
	J_PcapSocketImpl

#system path
INCLUDE_PATH+=-I/home/jm/jdk1.5.0_09/include \
			-I/home/jm/jdk1.5.0_09/include/linux

LIB_NAME=-lpcap 

-include common_lib.mk
